### ISSUE TITLE
Default all nodes collapsed

### ISSUE THREAD

**Issue by mikeerickson** [arvidkahl/vue-json-tree-view#1]
Hey there, nice work :-)

Is there a setting to have the data collapsed to begin with?

**Comment by mikeerickson** [comment]
Alternatively, can I procedurally collapse a specific node ?

**Comment by arvidkahl** [comment]
I just released v2.0 where the root component expects a `options` object. If you set `maxDepth` to 0, it should collapse all nodes.

Programmatic collapse if not implemented. How would you use such a feature? What functionality would you expect?

**Comment by mikeerickson** [comment]
Initial collapse is sufficient enough.

**Comment by arvidkahl** [comment]
It did make me think about the procedural collapse though. 

I was thinking about using an event-based internal communication (in the recursion), that would pass along a "path", like it's used in https://lodash.com/docs/4.17.4#set  . Like using `a[0].b.c` in an event such as `TreeView.$emit("closeNode", "a[0].b.c")`. Every node and leaf would carry their own path in the JSON object and react to the correct event. This could also allow for a mass collapse of a  subtree and all its subtrees. Would that be a useful approach? Or is there another way that i am missing?
