### ISSUE TITLE
 component lists rendered with v-for should have explicit keys.

### ISSUE THREAD

**Issue by slightlytrue** [arvidkahl/vue-json-tree-view#2]
[Vue tip]: <tree-view-item v-for="child in data.children">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info. 
(found in `<TreeViewItem>`)

Using:

    vue: V2.2.0
    vue-json-tree-view: V2.0.3

Created a Chrome Extension like JSONView using _VueJS_ and _vue-json-tree-view_ . Here is my [Repo](https://github.com/slightlytrue/JSONVue)

**Comment by arvidkahl** [comment]
any idea on how to give the lists unique keys when the component gets render recursively? i was thinking about that in #1 , what do you think about using JSON paths?

**Comment by jayarc** [comment]
Either of you have an example you can post of a v-for with unique keys that you don't get this error on when using it recursively?
